[package]
name = "crc_image_tool"
version = "0.1.0"
authors = ["PabloMansanet <pablomansanet@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc = "*"
clap = "3.0.0-beta.1"
byteorder = "*"
