#!/bin/bash

if [ "$1" != "" ]; then
    board="$1"
else
   echo "Choose a MCU:"
   echo " 1) STM32F429"
   echo " 2) STM32F469"
   echo " 3) STM32F407"
   read board
fi

if [ "$board" == "1" ]; then
   cargo build --target thumbv7em-none-eabi --no-default-features --features "stm32f429"
elif [ "$board" == "2" ]; then
   cargo build --target thumbv7em-none-eabi --no-default-features --features "stm32f469"
elif [ "$board" == "3" ]; then
   cargo build --target thumbv7em-none-eabi --no-default-features --features "stm32f407"
else
   echo "Usage: $0 [1|2|3]"
fi
