[workspace]
members = [
    "loadstone_config",
    "loadstone_front",
    "tools/confedit",
    "tools/signing_tool",
]

# Loadstone is excluded from the workspace, since its building is managed by x.py
exclude = [
    "loadstone",
]
