[package]
authors = ["PabloMansanet <pablomansanet@gmail.com>"]
edition = "2018"
readme = "README.md"
name = "secure_bootloader"
version = "0.1.0"

[dependencies]
cortex-m = "0.6.0"
cortex-m-rt = "0.6.10"
cortex-m-semihosting = "0.3.3"
panic-semihosting = "*"
nb = "*"
paste = "*"
casey = "*"

[dependencies.stm32f4]
version = "*"
features = ["stm32f429", "rt"]

[lib]
name = "secure_bootloader_lib"
test = true
bench = false

[[bin]]
name = "secure_bootloader"
test = true
bench = false

[profile.release]
codegen-units = 1 # better optimizations
debug = true # symbols are nice and they don't increase the size on Flash
lto = true # better optimizations
