[package]
edition = "2018"
readme = "README.md"
name = "loadstone"
version = "0.1.0"
default-run = "loadstone"

# The features below reflect the hierarchy of stm32 families.
# Choosing a f4 family implies f4, which implies stm32, which
# implies cortex M...

[features]
default = [
   "stm32f412_discovery",
   "defmt-default",
]
defmt-default = []
defmt-trace = []
defmt-debug = []
defmt-info = []
defmt-warn = []
defmt-error = []
stm32f412_discovery = ["stm32f412"]
stm32f429 = ["stm32f4/stm32f429", "stm32f4_any"]
stm32f469 = ["stm32f4/stm32f469", "stm32f4_any"]
stm32f407 = ["stm32f4/stm32f407", "stm32f4_any"]
stm32f412 = ["stm32f4/stm32f412", "stm32f4_any"]
stm32f4_any = ["stm32_any"]
stm32_any = ["cortex_m_any"]
cortex_m_any = []

[dependencies]
cortex-m = "0.6.0"
cortex-m-rt = "0.6.10"
cortex-m-semihosting = "0.3.3"
bluefruit_rust_hal = { path = "bluefruit_rust_hal" }
panic-abort = "*"
nb = "*"
paste = "*"
static_assertions = "*"
defmt = { git = "https://github.com/knurling-rs/defmt.git", branch = "main" }
defmt-rtt = { git = "https://github.com/knurling-rs/defmt.git", branch = "main" }

[dependencies.nom]
version = "*"
default-features = false

[dependencies.ufmt]
version = "*"
default-features = false

[dependencies.crc]
version = "*"
default-features = false

[dependencies.stm32f4]
version = "*"
features = ["rt"]

[lib]
name = "loadstone_lib"
test = true
bench = false

[[bin]]
name = "loadstone"
test = true
bench = false

[profile.release]
opt-level = "z"
codegen-units = 1 # better optimizations
debug = true # symbols are nice and they don't increase the size on Flash
lto = true # better optimizations

[profile.dev]
opt-level = 1 # Some optimization not to tank the binary size
codegen-units = 1 # better optimizations
lto = true # better optimizations
