//! Generates code from parsed .ron configuration. This is where
//! concrete Loadstone modules are constructed from user configuration
//! gathered from the web app GUI.

use std::{fs, path::Path};

use anyhow::Result;

use crate::Configuration;

mod memory_map;

pub fn generate_modules<P: AsRef<Path>>(loadstone_path: P, configuration: &Configuration) -> Result<()> {
    let autogenerated_folder_path = loadstone_path.as_ref().join("autogenerated");
    fs::create_dir(&autogenerated_folder_path).ok();
    memory_map::generate(autogenerated_folder_path, &configuration.memory_configuration)?;
    Ok(())
}
