#!/bin/bash

set -e

# Install prerequesites
apt-get update
apt-get install -y gcc curl # gdb-multiarch openocd qemu-system-arm

# Create user
adduser --disabled-password --gecos '' user
usermod -aG sudo user
