#!/bin/bash

set -e

# Install prerequisites
sudo apt-get update
sudo apt-get install -y gcc curl # gdb-multiarch openocd qemu-system-arm

# Install rust
curl https://sh.rustup.rs -sSf | sh -s -- -y
source $HOME/.cargo/env
rustup default nightly
rustup update
cargo install cargo-binutils
rustup component add llvm-tools-preview
rustup target add thumbv7em-none-eabi
