#!/bin/bash

set -e

TARGET_NAME=$(cat .cargo/.runner-target)

if [[ "$TARGET_NAME" = "stm32f412" ]]; then
    exec probe-run --chip STM32F412ZGTx $*
elif [[ "$TARGET_NAME" = "wgm160p" ]]; then
    exec .cargo/debug_wgm160p.sh $*
elif [[ "$TARGET_NAME" = "maxim32630" ]]; then
    exec .cargo/debug_max32630.sh $*
else
    echo "Failed to determine target platform. Refusing to run."
    exit 1
fi
