name: actions
on: [push, pull_request]
jobs:
  setup:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

  tests:
    needs: setup
    container: eu.gcr.io/bluefire-ci/loadstone-build:latest
    runs-on: self-hosted
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: true
      CARGO_TERM_VERBOSE: true
    steps:
      - name: Configure SSH
        run: |
          mkdir -p /home/user/.ssh/
          echo "${{ secrets.PATHFINDERDELL_KNOWN_HOSTS }}" >> /home/user/.ssh/known_hosts
          echo "${{ secrets.PATHFINDERDELL_PRIVATE_KEY }}" > /home/user/.ssh/id_rsa
          chmod 600 /home/user/.ssh/id_rsa
      - name: Tests
        run: cargo test
      - name: Loadstone Front Tests
        run: cd loadstone_front && cargo test

  stm32f412_discovery:
    needs: setup
    container: eu.gcr.io/bluefire-ci/loadstone-build:latest
    runs-on: self-hosted
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: true
      CARGO_TERM_VERBOSE: true
    steps:
      - name: Configure SSH
        run: |
          mkdir -p /home/user/.ssh/
          echo "${{ secrets.PATHFINDERDELL_KNOWN_HOSTS }}" >> /home/user/.ssh/known_hosts
          echo "${{ secrets.PATHFINDERDELL_PRIVATE_KEY }}" > /home/user/.ssh/id_rsa
          chmod 600 /home/user/.ssh/id_rsa
      - name: Build
        env:
          SCRIPT_MODE: true
        run: bash ./build_artifacts.sh stm32f412_discovery
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: stm32f412_discovery
          path: artifacts.zip

  wgm160p:
    needs: setup
    container: eu.gcr.io/bluefire-ci/loadstone-build:latest
    runs-on: self-hosted
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: true
      CARGO_TERM_VERBOSE: true
    steps:
      - name: Configure SSH
        run: |
          mkdir -p /home/user/.ssh/
          echo "${{ secrets.PATHFINDERDELL_KNOWN_HOSTS }}" >> /home/user/.ssh/known_hosts
          echo "${{ secrets.PATHFINDERDELL_PRIVATE_KEY }}" > /home/user/.ssh/id_rsa
          chmod 600 /home/user/.ssh/id_rsa
      - name: Build
        env:
          SCRIPT_MODE: true
        run: bash ./build_artifacts.sh wgm160p
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: wgm160p
          path: artifacts.zip
