name: actions
on: [push]
jobs:
  setup:
    runs-on: self-hosted
    steps:
      - name: Docker image
        run: docker build -t loadstonebuild docker/

  test:
    runs-on: self-hosted
    container: loadstonebuild:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Tests
        run: cargo test --release

  documentation:
    runs-on: self-hosted
    container: loadstonebuild:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Documentation
        run: ~/.cargo/bin/cargo d
      - name: Deploy Documentation
        if: contains(github.ref, 'staging')
        env:
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./target/thumbv7em-none-eabihf/doc
          SCRIPT_MODE: true
        run: |
          bash ./tools/deploy_docs.sh

  build:
    runs-on: self-hosted
    container: loadstonebuild:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        env:
          SCRIPT_MODE: true
        run: |
          cargo update
          bash ./build_artifacts.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: artifacts.zip
