name: actions
on: [push]
jobs:
  setup:
    runs-on: self-hosted
    steps:
      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  test:
    needs: setup
    runs-on: self-hosted
    container: bluefruitpathfinder/ubuntu-rust:latest
    steps:
      - name: Tests
        run: cargo test --release

  documentation:
    needs: setup
    runs-on: self-hosted
    container: bluefruitpathfinder/ubuntu-rust:latest
    steps:
      - name: Documentation
        run: ~/.cargo/bin/cargo d
      - name: Deploy Documentation
        if: contains(github.ref, 'staging')
        env:
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./target/thumbv7em-none-eabihf/doc
          SCRIPT_MODE: true
        run: |
          bash ./tools/deploy_docs.sh

  build:
    needs: setup
    runs-on: self-hosted
    container: bluefruitpathfinder/ubuntu-rust:latest
    steps:
      - name: Build
        env:
          SCRIPT_MODE: true
        run: |
          cargo update
          bash ./build_artifacts.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: artifacts.zip
