name: actions
on: [push]
jobs:
  test:
    runs-on: self-hosted
    container: rust:1.31
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cargo Initialisation
        run: |
          rustup default nightly
          rustup update
          rustup component add llvm-tools-preview
          rustup target add thumbv7em-none-eabihf
          cargo install cargo-binutils
      - name: Tests
        run: cargo test --release

  documentation:
    runs-on: self-hosted
    container: rust:1.31
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cargo Initialisation
        run: |
          rustup default nightly
          rustup update
          rustup component add llvm-tools-preview
          rustup target add thumbv7em-none-eabihf
          cargo install cargo-binutils
      - name: Documentation
        run: ~/.cargo/bin/cargo d
      - name: Deploy Documentation
        if: contains(github.ref, 'staging')
        env:
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./target/thumbv7em-none-eabihf/doc
          SCRIPT_MODE: true
        run: |
          bash ./tools/deploy_docs.sh

  build:
    runs-on: self-hosted
    container: rust:1.31
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cargo Initialisation
        run: |
          rustup default nightly
          rustup update
          rustup component add llvm-tools-preview
          rustup target add thumbv7em-none-eabihf
          cargo install cargo-binutils
      - name: Build
        env:
          SCRIPT_MODE: true
        run: |
          cargo update
          bash ./build_artifacts.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: artifacts.zip
