name: actions
on: [push]
jobs:
  docker-login:
    runs-on: self-hosted
    steps:
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

  build:
    needs: docker-login
    container: bluefruitpathfinder/loadstone-build:latest
    runs-on: self-hosted
    steps:
      - name: ssh-agent Setup
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.PATHFINDERDELL_PRIVATE_KEY }}
      - name: Tests
        shell: bash
        run: cargo test --release
      - name: Documentation
        shell: bash
        run: cargo d
      - name: Deploy Documentation
        if: contains(github.ref, 'staging')
        env:
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./target/thumbv7em-none-eabihf/doc
          SCRIPT_MODE: true
        shell: bash
        run: ./tools/deploy_docs.sh
      - name: Build
        shell: bash
        env:
          SCRIPT_MODE: true
        run: |
          cargo update
          ./build_artifacts.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: artifacts.zip
