name: actions
on: [push]
jobs:
  docker-login:
    runs-on: self-hosted
    steps:
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

  build-stm32f412_discovery:
    needs: docker-login
    container: bluefruitpathfinder/loadstone-build:latest
    runs-on: self-hosted
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: true
    steps:
      - name: Configure SSH
        run: |
          mkdir -p /home/user/.ssh/
          echo "${{ secrets.PATHFINDERDELL_KNOWN_HOSTS }}" >> /home/user/.ssh/known_hosts
          echo "${{ secrets.PATHFINDERDELL_PRIVATE_KEY }}" > /home/user/.ssh/id_rsa
          chmod 600 /home/user/.ssh/id_rsa
      - name: Tests
        run: cargo test --release --features stm32f412_discovery
      - name: Build
        env:
          SCRIPT_MODE: true
        run: |
          cargo update
          bash ./build_artifacts.sh stm32f412_discovery
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: artifacts.zip

  build-wgm160p:
    needs: docker-login
    container: bluefruitpathfinder/loadstone-build:latest
    runs-on: self-hosted
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: true
    steps:
      - name: Configure SSH
        run: |
          mkdir -p /home/user/.ssh/
          echo "${{ secrets.PATHFINDERDELL_KNOWN_HOSTS }}" >> /home/user/.ssh/known_hosts
          echo "${{ secrets.PATHFINDERDELL_PRIVATE_KEY }}" > /home/user/.ssh/id_rsa
          chmod 600 /home/user/.ssh/id_rsa
      - name: Tests
        run: cargo test --release --features wgm160p
      - name: Build
        env:
          SCRIPT_MODE: true
        run: |
          cargo update
          bash ./build_artifacts.sh wgm160p
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: artifacts.zip
