name: actions
on: [push]
jobs:
  docker-login:
    runs-on: self-hosted
    steps:
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

  build:
    needs: docker-login
    container: bluefruitpathfinder/loadstone-build:latest
    runs-on: self-hosted
    steps:
      - name: Configure SSH
        run: |
          mkdir -p /home/user/.ssh/
          echo "${{ secrets.PATHFINDERDELL_KNOWN_HOSTS }}" >> /home/user/.ssh/known_hosts
          echo "${{ secrets.PATHFINDERDELL_PRIVATE_KEY }}" > /home/user/.ssh/id_rsa
          chmod 600 /home/user/.ssh/id_rsa
          eval `ssh-agent -s`
          ssh-add /home/user/.ssh/id_rsa
      - name: Tests
        run: cargo test --release --vv
      - name: Documentation
        run: cargo d
      - name: Deploy Documentation
        if: contains(github.ref, 'staging')
        env:
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./target/thumbv7em-none-eabihf/doc
          SCRIPT_MODE: true
        run: ./tools/deploy_docs.sh
      - name: Build
        env:
          SCRIPT_MODE: true
        run: |
          cargo update
          ./build_artifacts.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: artifacts.zip
