name: Tests and Samples
on: [push, pull_request]
jobs:
  tests:
    container: bluefruitpathfinder/loadstone-build:latest
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_VERBOSE: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Loadstone tests
        run: ./x.py test /dev/null
      - name: Additional tests
        run: cargo test

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: clippy
            override: true
      - uses: actions-rs/clippy@master
        with:
          args: --all-features --all-targets

  # This job launches a few `cargo check` invocations using several config file samples, to exercise
  # the maximum amount of ports without taking time to compile final artifacts.
  sample_checks:
    container: bluefruitpathfinder/loadstone-build:latest
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_VERBOSE: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test step (find and stop)
        run: find ; false
      - name: Check sample stm32f4 build with external flash
        env:
          SCRIPT_MODE: true
        run: ./x.py check .github/workflows/examples/stm32f4_external.ron stm32f412
      - name: Check sample stm32f4 build without external flash
        env:
          SCRIPT_MODE: true
        run: ./x.py check .github/workflows/examples/stm32f4.ron stm32f412
      - name: Check sample wgm160p build
        env:
          SCRIPT_MODE: true
        run: ./x.py check .github/workflows/examples/wgm160p.ron wgm160p
      - name: Check sample stm32f4 build with encryption
        env:
          SCRIPT_MODE: true
        run: ./x.py check .github/workflows/examples/stm32f4_encrypted.ron stm32f412 ecdsa-verify
