name: dispatch
on:
   workflow_dispatch:
      inputs:
         loadstone_configuration:
            description: 'Loadstone configuration .ron file (inline)'
            required: true

         loadstone_features:
            description: 'Loadstone features (comma separated list)'
            required: true
            default: ''

jobs:
  setup:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

  embedded_build:
    needs: setup
    container: bluefruitpathfinder/loadstone-build:latest
    runs-on: self-hosted
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: true
      CARGO_TERM_VERBOSE: true
    steps:
      - name: Configure SSH
        run: |
          mkdir -p /home/user/.ssh/
          echo "${{ secrets.PATHFINDERDELL_KNOWN_HOSTS }}" >> /home/user/.ssh/known_hosts
          echo "${{ secrets.PATHFINDERDELL_PRIVATE_KEY }}" > /home/user/.ssh/id_rsa
          chmod 600 /home/user/.ssh/id_rsa
      - name: Build
        env:
          SCRIPT_MODE: true
        run: LOADSTONE_CONFIG='${{ github.event.inputs.loadstone_configuration }}' cargo objcopy --bin loadstone --release --target thumbv7em-none-eabihf --features ${{ github.event.inputs.loadstone_features }} -- -O binary loadstone.bin
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: loadstone.bin
          path: loadstone.bin
