name: dispatch
on:
   workflow_dispatch:
      inputs:
         loadstone_configuration:
            description: 'Loadstone configuration .ron file (inline)'
            required: true

         loadstone_features:
            description: 'Loadstone features (comma separated list)'
            required: true
            default: ''

jobs:
  setup:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

  embedded_build:
    needs: setup
    container: eu.gcr.io/bluefire-ci/loadstone-build:latest
    runs-on: self-hosted
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: true
      CARGO_TERM_VERBOSE: true
    steps:
      - name: Configure SSH
        run: |
          mkdir -p /home/user/.ssh/
          echo "${{ secrets.PATHFINDERDELL_KNOWN_HOSTS }}" >> /home/user/.ssh/known_hosts
          echo "${{ secrets.PATHFINDERDELL_PRIVATE_KEY }}" > /home/user/.ssh/id_rsa
          chmod 600 /home/user/.ssh/id_rsa
      - name: Build Loadstone
        env:
          SCRIPT_MODE: true
        run: LOADSTONE_CONFIG='${{ github.event.inputs.loadstone_configuration }}' cargo objcopy --bin loadstone --release --target thumbv7em-none-eabihf --features ${{ github.event.inputs.loadstone_features }} -- -O binary loadstone.bin
      - name: Build Demo App
        env:
          SCRIPT_MODE: true
        run: LOADSTONE_CONFIG='${{ github.event.inputs.loadstone_configuration }}' cargo objcopy --bin demo_app --release --target thumbv7em-none-eabihf --features relocate-to-bootable-bank,${{ github.event.inputs.loadstone_features }} -- -O binary demo_app.bin
      - name: Copy Ron File
        env:
          SCRIPT_MODE: true
        run: echo '${{ github.event.inputs.loadstone_configuration }}' > loadstone_config.ron
      - name: Upload Ron
        uses: actions/upload-artifact@v2
        with:
           name: loadstone_config.ron
           path: loadstone_config.ron
      - name: Upload Loadstone Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: loadstone.bin
          path: loadstone.bin
      - name: Upload Demo App Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: demo_app.bin
          path: demo_app.bin
